# Generated by Django 3.2.13 on 2022-06-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='preco_unit',
            new_name='descricao',
        ),
    ]
