# Generated by Django 3.2.13 on 2022-06-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_preco_unit_posts_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='descricao',
            field=models.TextField(max_length=200),
        ),
    ]
