# Generated by Django 3.2.13 on 2022-06-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
